# Generated by Django 4.1.2 on 2022-10-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("last_seen", models.DateTimeField()),
                ("avatar_img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Tags")),
                ("tag_description", models.TextField()),
                ("tags_accout", models.ManyToManyField(to="api.account")),
            ],
        ),
        migrations.CreateModel(
            name="WorkOuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="WorkOuts")),
                ("workout_type", models.CharField(max_length=30)),
                ("workout_category", models.CharField(max_length=30)),
                ("workout_intensity", models.IntegerField()),
                ("workout_duration", models.DurationField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("total_distance", models.IntegerField()),
                ("gps_coordinates", models.CharField(max_length=30)),
                (
                    "workout_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
                ("workout_tags", models.ManyToManyField(to="api.tags")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Post")),
                ("post", models.TextField()),
                ("post_img", models.ImageField(upload_to="")),
                ("post_date", models.DateTimeField()),
                ("post_likes", models.IntegerField()),
                (
                    "post_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Photo")),
                ("photo", models.ImageField(upload_to="")),
                (
                    "photo_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Groups")),
                ("group_description", models.TextField()),
                ("group_tags", models.ManyToManyField(to="api.tags")),
                ("member", models.ManyToManyField(to="api.account")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Comment")),
                ("comment", models.TextField()),
                (
                    "comment_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
                (
                    "comment_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.post",
                    ),
                ),
            ],
        ),
    ]
