# Generated by Django 4.1.2 on 2022-11-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags", old_name="tags_accout", new_name="tags_account",
        ),
    ]
