# Generated by Django 4.1.3 on 2022-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags_accout',
            new_name='tags_account',
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True),
        ),
    ]
