# Generated by Django 4.1.2 on 2022-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_tags_accout_tags_tags_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags", old_name="tags_account", new_name="tags_accout",
        ),
        migrations.AlterField(
            model_name="account",
            name="avatar_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_seen",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="groups",
            name="group_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="end_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="gps_coordinates",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="start_time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="total_distance",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="workout_category",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="workout_intensity",
            field=models.IntegerField(blank=True),
        ),
    ]
