# Generated by Django 4.1.3 on 2022-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tags_accout_tags_tags_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
