# Generated by Django 4.0.8 on 2022-11-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_avatar_img_alter_account_email_and_more'),
        ('api', '0003_rename_tags_account_tags_tags_accout_and_more'),
    ]

    operations = [
    ]
