# Generated by Django 4.0.8 on 2022-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workout_tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.tags'),
        ),
    ]
