# Generated by Django 4.1.3 on 2022-12-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_workouts_workout_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_name',
        ),
    ]
