# Generated by Django 4.1.3 on 2022-12-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_account_email_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_tags',
        ),
        migrations.RemoveField(
            model_name='workouts',
            name='workout_category',
        ),
        migrations.RemoveField(
            model_name='workouts',
            name='workout_tags',
        ),
        migrations.AlterField(
            model_name='workouts',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='name',
            field=models.CharField(max_length=30, verbose_name='WorkOut Name'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
