# Generated by Django 4.1.2 on 2022-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_rename_groups_workoutgroups_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="WorkoutGroups", new_name="Groups",),
        migrations.AlterField(
            model_name="groups",
            name="member",
            field=models.ManyToManyField(to="api.account"),
        ),
    ]
