# Generated by Django 4.1.2 on 2022-12-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_workoutgroups_groups_alter_groups_member"),
    ]

    operations = [
        migrations.RenameModel(old_name="Groups", new_name="WorkoutGroups",),
    ]
