# Generated by Django 4.1.2 on 2022-12-03 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0018_rename_groups_workoutgroups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutgroups",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
