# Generated by Django 4.1.2 on 2022-12-03 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0019_alter_workoutgroups_member"),
    ]

    operations = [
        migrations.RemoveField(model_name="workoutgroups", name="member",),
        migrations.AddField(
            model_name="workoutgroups",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
