# Generated by Django 4.1.2 on 2022-12-03 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0020_remove_workoutgroups_member_workoutgroups_member"),
    ]

    operations = [
        migrations.RemoveField(model_name="workoutgroups", name="member",),
        migrations.AddField(
            model_name="workoutgroups",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
