# Generated by Django 4.1.2 on 2022-12-05 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0021_remove_workoutgroups_member_workoutgroups_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutgroups",
            name="member",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="workoutgroups",
            name="name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Groups"),
        ),
    ]
