branch-defaults:
  default:
    environment: django-env-2
    group_suffix: null
global:
  application_name: FamFitnessDjango2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
